version: "3"
services:
  app:
    restart: always
    build: . # Current directory!
    command: "python3 ./ajirni/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=h3qbhJEq9c
      - MYSQL_DATABASE=tSfCCLaIkh
      - MYSQL_USER=tSfCCLaIkh
      - MYSQL_PASSWORD=h3qbhJEq9c
